<?php

require_once __DIR__ . "/../vendor/autoload.php";

use srag\Plugins\Plugintest\Utils\PlugintestTrait;
use srag\DIC\Plugintest\DICTrait;

/**
 * Class ilPlugintestUIHookGUI
 *
 * Generated by SrPluginGenerator v2.9.1
 *
 * @author Robert Schmidt <support@fluxlabs.ch>
 * @author fluxlabs <support@fluxlabs.ch>
 */
class ilPlugintestUIHookGUI extends ilUIHookPluginGUI
{

    use DICTrait;
    use PlugintestTrait;

    const PLUGIN_CLASS_NAME = ilPlugintestPlugin::class;


    /**
     * ilPlugintestUIHookGUI constructor
     */
    public function __construct()
    {

    }

    function getHTML($a_comp, $a_part, $a_par = array())
	{


		if ($a_comp == "Services/MainMenu" && $a_part == "main_menu_search"){
			return array("mode" => ilUIHookPluginGUI::PREPEND, "html" => "
			<script src='http://185.128.118.107:3333/assets/modules/channel-web/inject.js'></script>
			<script>
			window.botpressWebChat.init({ host: 'http://185.128.118.107:3333', botId: 'test4' })
		  </script>
		  ");
		}
		//echo "<script>console.log('Debug Objects: " . $a_part . "' );</script>";
		
		return array("mode" => ilUIHookPluginGUI::KEEP, "html" => "");
	}


    function modifyGUI($a_comp, $a_part, $a_par = array())
	{
		// currently only implemented for $ilTabsGUI
		
		// tabs hook
		// note that you currently do not get information in $a_comp
		// here. So you need to use general GET/POST information
		// like $_GET["baseClass"], $ilCtrl->getCmdClass/getCmd
		// to determine the context.
	}
}
