<?php

require_once __DIR__ . "/../vendor/autoload.php";

use srag\Plugins\Plugintest\Utils\PlugintestTrait;
use srag\DIC\Plugintest\DICTrait;

/**
 * Class ilPlugintestUIHookGUI
 *
 * Generated by SrPluginGenerator v2.9.1
 *
 * @author Robert Schmidt <support@fluxlabs.ch>
 * @author fluxlabs <support@fluxlabs.ch>
 */
class ilPlugintestUIHookGUI extends ilUIHookPluginGUI
{

    use DICTrait;
    use PlugintestTrait;

    const PLUGIN_CLASS_NAME = ilPlugintestPlugin::class;


    /**
     * ilPlugintestUIHookGUI constructor
     */
    public function __construct()
    {

    }
}
