<?php

require_once __DIR__ . "/../vendor/autoload.php";

use srag\Plugins\Plugintest\Utils\PlugintestTrait;
use ILIAS\DI\Container;
use srag\CustomInputGUIs\Plugintest\Loader\CustomInputGUIsLoaderDetector;
use srag\DevTools\Plugintest\DevToolsCtrl;
use srag\RemovePluginDataConfirm\Plugintest\PluginUninstallTrait;

/**
 * Class ilPlugintestPlugin
 *
 * Generated by SrPluginGenerator v2.9.1
 *
 * @author Robert Schmidt <support@fluxlabs.ch>
 * @author fluxlabs <support@fluxlabs.ch>
 */
class ilPlugintestPlugin extends ilUserInterfaceHookPlugin
{

    use PluginUninstallTrait;
    use PlugintestTrait;

    const PLUGIN_CLASS_NAME = self::class;
    const PLUGIN_ID = "plugintest";
    const PLUGIN_NAME = "Plugintest";
    /**
     * @var self|null
     */
    protected static $instance = null;


    /**
     * ilPlugintestPlugin constructor
     */
    public function __construct()
    {
        parent::__construct();
    }


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * @inheritDoc
     */
    public function exchangeUIRendererAfterInitialization(Container $dic) : Closure
    {
        return CustomInputGUIsLoaderDetector::exchangeUIRendererAfterInitialization();
    }


    /**
     * @inheritDoc
     */
    public function getPluginName() : string
    {
        return self::PLUGIN_NAME;
    }


    /**
     * @inheritDoc
     */
    public function updateLanguages(/*?array*/ $a_lang_keys = null) : void
    {
        parent::updateLanguages($a_lang_keys);

        $this->installRemovePluginDataConfirmLanguages();
    }


    /**
     * @inheritDoc
     */
    protected function deleteData() : void
    {
        self::plugintest()->dropTables();
    }


    /**
     * @inheritDoc
     */
    protected function shouldUseOneUpdateStepOnly() : bool
    {
        return false;
    }
}
