<?php

namespace srag\Plugins\Plugintest\Utils;

use srag\Plugins\Plugintest\Repository;

/**
 * Trait PlugintestTrait
 *
 * Generated by SrPluginGenerator v2.9.1
 *
 * @package srag\Plugins\Plugintest\Utils
 *
 * @author Robert Schmidt <support@fluxlabs.ch>
 * @author fluxlabs <support@fluxlabs.ch>
 */
trait PlugintestTrait
{

    /**
     * @return Repository
     */
    protected static function plugintest() : Repository
    {
        return Repository::getInstance();
    }
}
