<?php

namespace srag\Plugins\Plugintest;

use srag\Plugins\Plugintest\Config\Repository as ConfigRepository;
use srag\Plugins\Plugintest\Utils\PlugintestTrait;
use ilPlugintestPlugin;
use srag\DIC\Plugintest\DICTrait;

/**
 * Class Repository
 *
 * Generated by SrPluginGenerator v2.9.1
 *
 * @package srag\Plugins\Plugintest
 *
 * @author Robert Schmidt <support@fluxlabs.ch>
 * @author fluxlabs <support@fluxlabs.ch>
 */
final class Repository
{

    use DICTrait;
    use PlugintestTrait;

    const PLUGIN_CLASS_NAME = ilPlugintestPlugin::class;
    /**
     * @var self|null
     */
    protected static $instance = null;


    /**
     * Repository constructor
     */
    private function __construct()
    {

    }


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * @return ConfigRepository
     */
    public function config() : ConfigRepository
    {
        return ConfigRepository::getInstance();
    }


    /**
     *
     */
    public function dropTables() : void
    {
        $this->config()->dropTables();
    }


    /**
     *
     */
    public function installTables() : void
    {
        $this->config()->installTables();
    }
}
